/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4709a39-2adf-433e-b94d-2b343073c33f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_P27Il6wTG",
    "aws_user_pools_web_client_id": "4696g030t1s0g5q8ivuq0lmdrk",
    "oauth": {
        "domain": "parknarcsf3377c15-f3377c15-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/signin/",
        "redirectSignOut": "http://localhost:3000/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://joybbpjcffc75g2ufvg6xu6cc4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xhpljgq26fek7dnszy4hwxsaae",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "parknarcsdb-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "parknarcsimagestore202701-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
