import {createAsyncThunk, createSlice, PayloadAction} from '@reduxjs/toolkit';
import NarcService, {NarcReport, NarcRequest} from "./submission/narc.service";
import {RootState} from "../../app/store";

export interface NarcState {
}

const initialState: NarcState = {};

export const narcABitchOut = createAsyncThunk('narcs/narcABitchOut', async (payload: NarcRequest, thunkAPI) => {
    const userId = (thunkAPI.getState() as RootState).user.userId;
    return userId ?
        NarcService.narc({
            ...payload,
            date: new Date().toISOString(),
            postedBy: userId
        })
        : Promise.reject('Not signed in');
})

export const narcSlice = createSlice({
    name: 'narcs',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => builder
});



// export const selectCount = (state: RootState) => state.counter.value;

export default narcSlice.reducer;
